## Preprocessing

In [56]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [57]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN','NAME' ], inplace=True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [58]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [59]:
# Look at APPLICATION_TYPE value counts for binning
types = application_df['APPLICATION_TYPE'].value_counts()
types

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [60]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(types.iloc[8:].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [61]:
# Look at CLASSIFICATION value counts for binning
classification = application_df['CLASSIFICATION'].value_counts()
classification

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [62]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification[classification>1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [63]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification.iloc[5:].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [64]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [65]:
# Split our preprocessed data into our features and target arrays
y = dummies_df['IS_SUCCESSFUL'].values
X = dummies_df.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=78, test_size=0.2)

In [66]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [67]:
# Create a method that creates a new Sequential model with hyperparameter options
input_features = len(X_train[0])
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=2*input_features,
        max_value=3*input_features,
        step=2), activation=hp.Choice('activation',['relu','tanh','sigmoid']), input_dim=input_features))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=2*input_features,
            max_value=3*input_features,
            step=2),
            activation=hp.Choice('activation',['relu','tanh','sigmoid'])))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [68]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

In [69]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 60 Complete [00h 00m 21s]
val_accuracy: 0.725218653678894

Best val_accuracy So Far: 0.7279883623123169
Total elapsed time: 00h 07m 23s

In [70]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'first_units': 124,
 'activation': 'relu',
 'num_layers': 2,
 'units_0': 92,
 'units_1': 90,
 'units_2': 88,
 'units_3': 108,
 'units_4': 126,
 'units_5': 128,
 'tuner/epochs': 20,
 'tuner/initial_epoch': 0,
 'tuner/bracket': 0,
 'tuner/round': 0}

In [71]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
best_model.fit(X_train_scaled, y_train, epochs=200)

Epoch 1/200
858/858 [==============================] - 1s 663us/step - loss: 0.5482 - accuracy: 0.7339
Epoch 2/200
858/858 [==============================] - 1s 668us/step - loss: 0.5475 - accuracy: 0.7356
Epoch 3/200
858/858 [==============================] - 1s 668us/step - loss: 0.5465 - accuracy: 0.7349
Epoch 4/200
858/858 [==============================] - 1s 709us/step - loss: 0.5469 - accuracy: 0.7348
Epoch 5/200
858/858 [==============================] - 1s 748us/step - loss: 0.5450 - accuracy: 0.7362
Epoch 6/200
858/858 [==============================] - 1s 696us/step - loss: 0.5452 - accuracy: 0.7368
Epoch 7/200
858/858 [==============================] - 1s 691us/step - loss: 0.5448 - accuracy: 0.7369
Epoch 8/200
858/858 [==============================] - 1s 668us/step - loss: 0.5437 - accuracy: 0.7382
Epoch 9/200
858/858 [==============================] - 1s 667us/step - loss: 0.5443 - accuracy: 0.7365
Epoch 10/200
858/858 [==============================] - 1s 668us/step - loss: 0.5435 - accuracy: 0.7377
Epoch 11/200
858/858 [==============================] - 1s 680us/step - loss: 0.5432 - accuracy: 0.7379
Epoch 12/200
858/858 [==============================] - 1s 677us/step - loss: 0.5430 - accuracy: 0.7382
Epoch 13/200
858/858 [==============================] - 1s 687us/step - loss: 0.5424 - accuracy: 0.7380
Epoch 14/200
858/858 [==============================] - 1s 670us/step - loss: 0.5422 - accuracy: 0.7377
Epoch 15/200
858/858 [==============================] - 1s 673us/step - loss: 0.5413 - accuracy: 0.7385
Epoch 16/200
858/858 [==============================] - 1s 672us/step - loss: 0.5419 - accuracy: 0.7381
Epoch 17/200
858/858 [==============================] - 1s 681us/step - loss: 0.5411 - accuracy: 0.7387
Epoch 18/200
858/858 [==============================] - 1s 715us/step - loss: 0.5406 - accuracy: 0.7394
Epoch 19/200
858/858 [==============================] - 1s 698us/step - loss: 0.5407 - accuracy: 0.7390
Epoch 20/200
858/858 [==============================] - 1s 685us/step - loss: 0.5403 - accuracy: 0.7393
Epoch 21/200
858/858 [==============================] - 1s 673us/step - loss: 0.5406 - accuracy: 0.7383
Epoch 22/200
858/858 [==============================] - 1s 667us/step - loss: 0.5401 - accuracy: 0.7391
Epoch 23/200
858/858 [==============================] - 1s 688us/step - loss: 0.5403 - accuracy: 0.7392
Epoch 24/200
858/858 [==============================] - 1s 664us/step - loss: 0.5397 - accuracy: 0.7392
Epoch 25/200
858/858 [==============================] - 1s 666us/step - loss: 0.5399 - accuracy: 0.7394
Epoch 26/200
858/858 [==============================] - 1s 672us/step - loss: 0.5394 - accuracy: 0.7393
Epoch 27/200
858/858 [==============================] - 1s 686us/step - loss: 0.5389 - accuracy: 0.7397
Epoch 28/200
858/858 [==============================] - 1s 669us/step - loss: 0.5387 - accuracy: 0.7391
Epoch 29/200
858/858 [==============================] - 1s 677us/step - loss: 0.5382 - accuracy: 0.7392
Epoch 30/200
858/858 [==============================] - 1s 672us/step - loss: 0.5387 - accuracy: 0.7398
Epoch 31/200
858/858 [==============================] - 1s 669us/step - loss: 0.5382 - accuracy: 0.7408
Epoch 32/200
858/858 [==============================] - 1s 672us/step - loss: 0.5386 - accuracy: 0.7401
Epoch 33/200
858/858 [==============================] - 1s 685us/step - loss: 0.5376 - accuracy: 0.7406
Epoch 34/200
858/858 [==============================] - 1s 670us/step - loss: 0.5378 - accuracy: 0.7411
Epoch 35/200
858/858 [==============================] - 1s 670us/step - loss: 0.5374 - accuracy: 0.7412
Epoch 36/200
858/858 [==============================] - 1s 675us/step - loss: 0.5375 - accuracy: 0.7396
Epoch 37/200
858/858 [==============================] - 1s 692us/step - loss: 0.5376 - accuracy: 0.7403
Epoch 38/200
858/858 [==============================] - 1s 689us/step - loss: 0.5373 - accuracy: 0.7405
Epoch 39/200
858/858 [==============================] - 1s 693us/step - loss: 0.5368 - accuracy: 0.7405
Epoch 40/200
858/858 [==============================] - 1s 696us/step - loss: 0.5369 - accuracy: 0.7408
Epoch 41/200
858/858 [==============================] - 1s 694us/step - loss: 0.5364 - accuracy: 0.7407
Epoch 42/200
858/858 [==============================] - 1s 706us/step - loss: 0.5361 - accuracy: 0.7407
Epoch 43/200
858/858 [==============================] - 1s 667us/step - loss: 0.5360 - accuracy: 0.7412
Epoch 44/200
858/858 [==============================] - 1s 660us/step - loss: 0.5366 - accuracy: 0.7397
Epoch 45/200
858/858 [==============================] - 1s 671us/step - loss: 0.5366 - accuracy: 0.7410
Epoch 46/200
858/858 [==============================] - 1s 682us/step - loss: 0.5364 - accuracy: 0.7411
Epoch 47/200
858/858 [==============================] - 1s 672us/step - loss: 0.5358 - accuracy: 0.7406
Epoch 48/200
858/858 [==============================] - 1s 674us/step - loss: 0.5370 - accuracy: 0.7418
Epoch 49/200
858/858 [==============================] - 1s 669us/step - loss: 0.5359 - accuracy: 0.7408
Epoch 50/200
858/858 [==============================] - 1s 684us/step - loss: 0.5358 - accuracy: 0.7412
Epoch 51/200
858/858 [==============================] - 1s 664us/step - loss: 0.5356 - accuracy: 0.7410
Epoch 52/200
858/858 [==============================] - 1s 678us/step - loss: 0.5352 - accuracy: 0.7413
Epoch 53/200
858/858 [==============================] - 1s 664us/step - loss: 0.5355 - accuracy: 0.7410
Epoch 54/200
858/858 [==============================] - 1s 667us/step - loss: 0.5364 - accuracy: 0.7415
Epoch 55/200
858/858 [==============================] - 1s 681us/step - loss: 0.5349 - accuracy: 0.7417
Epoch 56/200
858/858 [==============================] - 1s 667us/step - loss: 0.5355 - accuracy: 0.7418
Epoch 57/200
858/858 [==============================] - 1s 675us/step - loss: 0.5352 - accuracy: 0.7415
Epoch 58/200
858/858 [==============================] - 1s 683us/step - loss: 0.5347 - accuracy: 0.7417
Epoch 59/200
858/858 [==============================] - 1s 692us/step - loss: 0.5348 - accuracy: 0.7416
Epoch 60/200
858/858 [==============================] - 1s 674us/step - loss: 0.5348 - accuracy: 0.7417
Epoch 61/200
858/858 [==============================] - 1s 672us/step - loss: 0.5347 - accuracy: 0.7422
Epoch 62/200
858/858 [==============================] - 1s 670us/step - loss: 0.5345 - accuracy: 0.7419
Epoch 63/200
858/858 [==============================] - 1s 672us/step - loss: 0.5347 - accuracy: 0.7418
Epoch 64/200
858/858 [==============================] - 1s 685us/step - loss: 0.5341 - accuracy: 0.7418
Epoch 65/200
858/858 [==============================] - 1s 665us/step - loss: 0.5359 - accuracy: 0.7416
Epoch 66/200
858/858 [==============================] - 1s 680us/step - loss: 0.5343 - accuracy: 0.7416
Epoch 67/200
858/858 [==============================] - 1s 670us/step - loss: 0.5337 - accuracy: 0.7417
Epoch 68/200
858/858 [==============================] - 1s 689us/step - loss: 0.5336 - accuracy: 0.7417
Epoch 69/200
858/858 [==============================] - 1s 671us/step - loss: 0.5341 - accuracy: 0.7423
Epoch 70/200
858/858 [==============================] - 1s 676us/step - loss: 0.5338 - accuracy: 0.7419
Epoch 71/200
858/858 [==============================] - 1s 669us/step - loss: 0.5337 - accuracy: 0.7422
Epoch 72/200
858/858 [==============================] - 1s 692us/step - loss: 0.5340 - accuracy: 0.7422
Epoch 73/200
858/858 [==============================] - 1s 666us/step - loss: 0.5333 - accuracy: 0.7425
Epoch 74/200
858/858 [==============================] - 1s 665us/step - loss: 0.5346 - accuracy: 0.7415
Epoch 75/200
858/858 [==============================] - 1s 664us/step - loss: 0.5346 - accuracy: 0.7414
Epoch 76/200
858/858 [==============================] - 1s 677us/step - loss: 0.5342 - accuracy: 0.7419
Epoch 77/200
858/858 [==============================] - 1s 685us/step - loss: 0.5338 - accuracy: 0.7422
Epoch 78/200
858/858 [==============================] - 1s 671us/step - loss: 0.5337 - accuracy: 0.7424
Epoch 79/200
858/858 [==============================] - 1s 673us/step - loss: 0.5337 - accuracy: 0.7426
Epoch 80/200
858/858 [==============================] - 1s 669us/step - loss: 0.5338 - accuracy: 0.7425
Epoch 81/200
858/858 [==============================] - 1s 681us/step - loss: 0.5336 - accuracy: 0.7423
Epoch 82/200
858/858 [==============================] - 1s 673us/step - loss: 0.5341 - accuracy: 0.7422
Epoch 83/200
858/858 [==============================] - 1s 678us/step - loss: 0.5330 - accuracy: 0.7426
Epoch 84/200
858/858 [==============================] - 1s 668us/step - loss: 0.5333 - accuracy: 0.7422
Epoch 85/200
858/858 [==============================] - 1s 680us/step - loss: 0.5329 - accuracy: 0.7424
Epoch 86/200
858/858 [==============================] - 1s 669us/step - loss: 0.5332 - accuracy: 0.7420
Epoch 87/200
858/858 [==============================] - 1s 662us/step - loss: 0.5336 - accuracy: 0.7424
Epoch 88/200
858/858 [==============================] - 1s 680us/step - loss: 0.5332 - accuracy: 0.7423
Epoch 89/200
858/858 [==============================] - 1s 676us/step - loss: 0.5329 - accuracy: 0.7422
Epoch 90/200
858/858 [==============================] - 1s 689us/step - loss: 0.5336 - accuracy: 0.7422
Epoch 91/200
858/858 [==============================] - 1s 673us/step - loss: 0.5330 - accuracy: 0.7424
Epoch 92/200
858/858 [==============================] - 1s 672us/step - loss: 0.5331 - accuracy: 0.7422
Epoch 93/200
858/858 [==============================] - 1s 684us/step - loss: 0.5328 - accuracy: 0.7428
Epoch 94/200
858/858 [==============================] - 1s 685us/step - loss: 0.5331 - accuracy: 0.7420
Epoch 95/200
858/858 [==============================] - 1s 695us/step - loss: 0.5326 - accuracy: 0.7424
Epoch 96/200
858/858 [==============================] - 1s 692us/step - loss: 0.5333 - accuracy: 0.7422
Epoch 97/200
858/858 [==============================] - 1s 686us/step - loss: 0.5328 - accuracy: 0.7428
Epoch 98/200
858/858 [==============================] - 1s 729us/step - loss: 0.5329 - accuracy: 0.7422
Epoch 99/200
858/858 [==============================] - 1s 729us/step - loss: 0.5328 - accuracy: 0.7422
Epoch 100/200
858/858 [==============================] - 1s 693us/step - loss: 0.5323 - accuracy: 0.7426
Epoch 101/200
858/858 [==============================] - 1s 708us/step - loss: 0.5329 - accuracy: 0.7424
Epoch 102/200
858/858 [==============================] - 1s 725us/step - loss: 0.5332 - accuracy: 0.7423
Epoch 103/200
858/858 [==============================] - 1s 721us/step - loss: 0.5326 - accuracy: 0.7422
Epoch 104/200
858/858 [==============================] - 1s 687us/step - loss: 0.5324 - accuracy: 0.7423
Epoch 105/200
858/858 [==============================] - 1s 747us/step - loss: 0.5326 - accuracy: 0.7423
Epoch 106/200
858/858 [==============================] - 1s 757us/step - loss: 0.5327 - accuracy: 0.7426
Epoch 107/200
858/858 [==============================] - 1s 741us/step - loss: 0.5327 - accuracy: 0.7427
Epoch 108/200
858/858 [==============================] - 1s 715us/step - loss: 0.5322 - accuracy: 0.7424
Epoch 109/200
858/858 [==============================] - 1s 724us/step - loss: 0.5323 - accuracy: 0.7424
Epoch 110/200
858/858 [==============================] - 1s 738us/step - loss: 0.5331 - accuracy: 0.7423
Epoch 111/200
858/858 [==============================] - 1s 729us/step - loss: 0.5325 - accuracy: 0.7424
Epoch 112/200
858/858 [==============================] - 1s 769us/step - loss: 0.5328 - accuracy: 0.7423
Epoch 113/200
858/858 [==============================] - 1s 695us/step - loss: 0.5326 - accuracy: 0.7418
Epoch 114/200
858/858 [==============================] - 1s 749us/step - loss: 0.5337 - accuracy: 0.7424
Epoch 115/200
858/858 [==============================] - 1s 761us/step - loss: 0.5323 - accuracy: 0.7429
Epoch 116/200
858/858 [==============================] - 1s 704us/step - loss: 0.5320 - accuracy: 0.7424
Epoch 117/200
858/858 [==============================] - 1s 719us/step - loss: 0.5327 - accuracy: 0.7424
Epoch 118/200
858/858 [==============================] - 1s 725us/step - loss: 0.5324 - accuracy: 0.7424
Epoch 119/200
858/858 [==============================] - 1s 744us/step - loss: 0.5325 - accuracy: 0.7429
Epoch 120/200
858/858 [==============================] - 1s 710us/step - loss: 0.5323 - accuracy: 0.7423
Epoch 121/200
858/858 [==============================] - 1s 684us/step - loss: 0.5325 - accuracy: 0.7426
Epoch 122/200
858/858 [==============================] - 1s 701us/step - loss: 0.5323 - accuracy: 0.7426
Epoch 123/200
858/858 [==============================] - 1s 753us/step - loss: 0.5320 - accuracy: 0.7427
Epoch 124/200
858/858 [==============================] - 1s 764us/step - loss: 0.5319 - accuracy: 0.7428
Epoch 125/200
858/858 [==============================] - 1s 770us/step - loss: 0.5315 - accuracy: 0.7428
Epoch 126/200
858/858 [==============================] - 1s 727us/step - loss: 0.5320 - accuracy: 0.7430
Epoch 127/200
858/858 [==============================] - 1s 697us/step - loss: 0.5326 - accuracy: 0.7430
Epoch 128/200
858/858 [==============================] - 1s 703us/step - loss: 0.5318 - accuracy: 0.7426
Epoch 129/200
858/858 [==============================] - 1s 673us/step - loss: 0.5322 - accuracy: 0.7428
Epoch 130/200
858/858 [==============================] - 1s 677us/step - loss: 0.5325 - accuracy: 0.7430
Epoch 131/200
858/858 [==============================] - 1s 717us/step - loss: 0.5317 - accuracy: 0.7433
Epoch 132/200
858/858 [==============================] - 1s 737us/step - loss: 0.5320 - accuracy: 0.7429
Epoch 133/200
858/858 [==============================] - 1s 701us/step - loss: 0.5314 - accuracy: 0.7427
Epoch 134/200
858/858 [==============================] - 1s 697us/step - loss: 0.5326 - accuracy: 0.7425
Epoch 135/200
858/858 [==============================] - 1s 682us/step - loss: 0.5317 - accuracy: 0.7430
Epoch 136/200
858/858 [==============================] - 1s 723us/step - loss: 0.5324 - accuracy: 0.7426
Epoch 137/200
858/858 [==============================] - 1s 697us/step - loss: 0.5322 - accuracy: 0.7426
Epoch 138/200
858/858 [==============================] - 1s 671us/step - loss: 0.5315 - accuracy: 0.7430
Epoch 139/200
858/858 [==============================] - 1s 674us/step - loss: 0.5321 - accuracy: 0.7427
Epoch 140/200
858/858 [==============================] - 1s 683us/step - loss: 0.5314 - accuracy: 0.7429
Epoch 141/200
858/858 [==============================] - 1s 672us/step - loss: 0.5312 - accuracy: 0.7431
Epoch 142/200
858/858 [==============================] - 1s 721us/step - loss: 0.5312 - accuracy: 0.7429
Epoch 143/200
858/858 [==============================] - 1s 694us/step - loss: 0.5313 - accuracy: 0.7431
Epoch 144/200
858/858 [==============================] - 1s 725us/step - loss: 0.5327 - accuracy: 0.7425
Epoch 145/200
858/858 [==============================] - 1s 682us/step - loss: 0.5324 - accuracy: 0.7427
Epoch 146/200
858/858 [==============================] - 1s 694us/step - loss: 0.5324 - accuracy: 0.7426
Epoch 147/200
858/858 [==============================] - 1s 686us/step - loss: 0.5320 - accuracy: 0.7428
Epoch 148/200
858/858 [==============================] - 1s 706us/step - loss: 0.5315 - accuracy: 0.7430
Epoch 149/200
858/858 [==============================] - 1s 699us/step - loss: 0.5311 - accuracy: 0.7428
Epoch 150/200
858/858 [==============================] - 1s 698us/step - loss: 0.5313 - accuracy: 0.7423
Epoch 151/200
858/858 [==============================] - 1s 680us/step - loss: 0.5313 - accuracy: 0.7430
Epoch 152/200
858/858 [==============================] - 1s 688us/step - loss: 0.5312 - accuracy: 0.7432
Epoch 153/200
858/858 [==============================] - 1s 667us/step - loss: 0.5320 - accuracy: 0.7428
Epoch 154/200
858/858 [==============================] - 1s 669us/step - loss: 0.5306 - accuracy: 0.7429
Epoch 155/200
858/858 [==============================] - 1s 705us/step - loss: 0.5313 - accuracy: 0.7434
Epoch 156/200
858/858 [==============================] - 1s 738us/step - loss: 0.5347 - accuracy: 0.7427
Epoch 157/200
858/858 [==============================] - 1s 718us/step - loss: 0.5316 - accuracy: 0.7433
Epoch 158/200
858/858 [==============================] - 1s 700us/step - loss: 0.5313 - accuracy: 0.7432
Epoch 159/200
858/858 [==============================] - 1s 704us/step - loss: 0.5312 - accuracy: 0.7430
Epoch 160/200
858/858 [==============================] - 1s 758us/step - loss: 0.5307 - accuracy: 0.7429
Epoch 161/200
858/858 [==============================] - 1s 749us/step - loss: 0.5315 - accuracy: 0.7430
Epoch 162/200
858/858 [==============================] - 1s 715us/step - loss: 0.5314 - accuracy: 0.7427
Epoch 163/200
858/858 [==============================] - 1s 686us/step - loss: 0.5310 - accuracy: 0.7429
Epoch 164/200
858/858 [==============================] - 1s 672us/step - loss: 0.5338 - accuracy: 0.7428
Epoch 165/200
858/858 [==============================] - 1s 691us/step - loss: 0.5314 - accuracy: 0.7427
Epoch 166/200
858/858 [==============================] - 1s 756us/step - loss: 0.5329 - accuracy: 0.7430
Epoch 167/200
858/858 [==============================] - 1s 747us/step - loss: 0.5314 - accuracy: 0.7430
Epoch 168/200
858/858 [==============================] - 1s 728us/step - loss: 0.5317 - accuracy: 0.7428
Epoch 169/200
858/858 [==============================] - 1s 700us/step - loss: 0.5313 - accuracy: 0.7432
Epoch 170/200
858/858 [==============================] - 1s 693us/step - loss: 0.5319 - accuracy: 0.7423
Epoch 171/200
858/858 [==============================] - 1s 697us/step - loss: 0.5310 - accuracy: 0.7432
Epoch 172/200
858/858 [==============================] - 1s 714us/step - loss: 0.5313 - accuracy: 0.7433
Epoch 173/200
858/858 [==============================] - 1s 697us/step - loss: 0.5313 - accuracy: 0.7426
Epoch 174/200
858/858 [==============================] - 1s 692us/step - loss: 0.5305 - accuracy: 0.7428
Epoch 175/200
858/858 [==============================] - 1s 689us/step - loss: 0.5310 - accuracy: 0.7429
Epoch 176/200
858/858 [==============================] - 1s 692us/step - loss: 0.5308 - accuracy: 0.7431
Epoch 177/200
858/858 [==============================] - 1s 676us/step - loss: 0.5307 - accuracy: 0.7430
Epoch 178/200
858/858 [==============================] - 1s 671us/step - loss: 0.5310 - accuracy: 0.7433
Epoch 179/200
858/858 [==============================] - 1s 670us/step - loss: 0.5314 - accuracy: 0.7431
Epoch 180/200
858/858 [==============================] - 1s 686us/step - loss: 0.5316 - accuracy: 0.7429
Epoch 181/200
858/858 [==============================] - 1s 667us/step - loss: 0.5317 - accuracy: 0.7426
Epoch 182/200
858/858 [==============================] - 1s 707us/step - loss: 0.5312 - accuracy: 0.7428
Epoch 183/200
858/858 [==============================] - 1s 668us/step - loss: 0.5307 - accuracy: 0.7429
Epoch 184/200
858/858 [==============================] - 1s 685us/step - loss: 0.5308 - accuracy: 0.7431
Epoch 185/200
858/858 [==============================] - 1s 699us/step - loss: 0.5303 - accuracy: 0.7431
Epoch 186/200
858/858 [==============================] - 1s 724us/step - loss: 0.8905 - accuracy: 0.7421
Epoch 187/200
858/858 [==============================] - 1s 684us/step - loss: 0.5311 - accuracy: 0.7430
Epoch 188/200
858/858 [==============================] - 1s 672us/step - loss: 0.5305 - accuracy: 0.7430
Epoch 189/200
858/858 [==============================] - 1s 683us/step - loss: 0.5301 - accuracy: 0.7434
Epoch 190/200
858/858 [==============================] - 1s 688us/step - loss: 0.5312 - accuracy: 0.7433
Epoch 191/200
858/858 [==============================] - 1s 704us/step - loss: 0.5302 - accuracy: 0.7433
Epoch 192/200

In [72]:
# Evaluate the model using the test data
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.6191 - accuracy: 0.7230 - 114ms/epoch - 528us/step
Loss: 0.6190938353538513, Accuracy: 0.7230320572853088

In [74]:
# Export our model to HDF5 file
best_model.save('./AlphabetSoupCharity_Optimization.h5',save_format='h5')

/Users/hanenzeddini/anaconda3/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(